# Generated by Django 2.2.4 on 2019-08-13 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date_issued', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('date_due', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('interest', models.IntegerField()),
                ('agent_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='officers.Agents')),
                ('customer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='officers.Customers')),
                ('office_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='officers.Officers')),
            ],
        ),
    ]
