# Generated by Django 2.2.4 on 2019-08-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agents',
            table='agents',
        ),
    ]
