# Generated by Django 2.2.4 on 2019-08-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_auto_20190817_1800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='loans',
            table='loans',
        ),
        migrations.AlterModelTable(
            name='officers',
            table='officers',
        ),
    ]
