# Generated by Django 2.2.4 on 2019-08-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_auto_20190817_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='nationa_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='nationa_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='nationa_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
